version: '3.7'

services:
  nginx:
    image: nginx:1.17.4
    working_dir: /app
    ports:
      - '80:80'
    volumes:
      - ../public:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm.docker
    working_dir: /app
    volumes:
      - ../:/app
    env_file:
      - ../.env.local

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - slack-bot-data:/var/lib/mysql
    env_file:
      - ../.env.local

volumes:
  slack-bot-data: